In [1]:
import numpy as np

### Случайные величины

In [13]:
a = [0, 1, 2, 3, 4, 5, 6]

In [29]:
p = [0, 0, 0, 0, 0, 0.9, 0.1]

In [31]:
np.random.choice(a=a, size=9)

array([3, 2, 4, 3, 0, 5, 5, 0, 2])

In [32]:
b = np.array([1, 2, 3, 4, 5])
np.random.shuffle(b)

In [33]:
b

array([5, 2, 4, 1, 3])

In [34]:
b = np.array([1, 2, 3, 4, 5])

In [37]:
c = np.random.permutation(b)

In [36]:
b

array([1, 2, 3, 4, 5])

In [38]:
c

array([2, 1, 5, 3, 4])

In [41]:
np.random.permutation(10)

array([9, 0, 3, 1, 4, 2, 8, 7, 5, 6])

In [45]:
np.random.sample()

0.46907236959983656

In [46]:
np.random.rand(2, 3, 5)

array([[[0.88866929, 0.77501809, 0.00214648, 0.87332671, 0.17840778],
        [0.94385273, 0.8501209 , 0.71730887, 0.71834193, 0.92697704],
        [0.15313563, 0.5219587 , 0.85442106, 0.59637859, 0.16600231]],

       [[0.61514537, 0.52676229, 0.2395906 , 0.59646546, 0.98509604],
        [0.55699323, 0.13956731, 0.46795562, 0.07434243, 0.14691156],
        [0.05982123, 0.40514361, 0.08117749, 0.30373108, 0.47255186]]])

In [48]:
np.random.randint(5, 10, size=20)

array([8, 6, 6, 6, 5, 8, 5, 8, 8, 8, 7, 9, 8, 6, 6, 6, 7, 6, 5, 7])

In [49]:
np.random.normal(5, 2.5, 100)

array([ 3.0821401 ,  9.0834205 , 10.16698809,  1.80942396,  2.53005503,
        6.69393288, 11.21975888,  3.30492774,  5.67960622,  6.20975578,
        2.9658395 ,  4.23022888, -1.2739587 ,  2.16764374,  6.20359717,
        5.11362021,  2.04982526,  5.33333448,  7.94191051,  5.30063549,
       -0.05879056,  0.7989338 ,  5.24868728,  3.32197242,  4.77314912,
        7.65891947,  5.35369873,  9.71293796,  4.9823389 ,  0.3102678 ,
        6.47438866,  4.31977053,  4.73133146,  2.16786626,  6.77645673,
        6.72899492,  3.16915522,  7.87444584,  7.34481577,  0.54154795,
        4.5094348 ,  1.92608754,  3.49109677,  2.35269022,  6.3179499 ,
        2.51270696,  3.69972661,  5.74683164,  6.33806971,  5.11842937,
        3.42884707,  3.68535161,  3.78564366,  7.56510499,  7.88511333,
        2.30615426,  3.40899519,  6.08330783,  5.65686953,  7.20190741,
        4.10531939,  4.29351544,  9.05824988,  2.73045802,  6.93601676,
        5.4265795 ,  4.64324028,  6.64437463,  7.46641888,  5.14

In [51]:
np.random.

8.568602793719666