In [1]:
import numpy as np

### Броадкастинг

In [18]:
x = np.array([1, 2, 3])
a = 5

In [19]:
x*a

array([ 5, 10, 15])

x = [1, 2, 3]
a = 5 -> a = [5, 5, 5]

In [ ]:
x = np.ones((2, 3, 5, 1))
y = np.ones((2, 1, 5, 8))

x*y

In [22]:
c = x*y
c.shape

(2, 3, 5, 8)

In [23]:
x.shape, y.shape

((2, 3, 5, 1), (2, 1, 5, 8))

In [24]:
x = np.ones((3, 5, 1))
y = np.ones((2, 1, 5, 8))


In [25]:
z = x*y
z.shape

(2, 3, 5, 8)

In [26]:
x = np.ones((3, 5, 1))
y = np.ones((2, 4, 5, 8))

x*y

ValueError: operands could not be broadcast together with shapes (3,5,1) (2,4,5,8) 

In [27]:
a = np.ones((3, 5, 4, 1))

In [28]:
a.shape, a.ndim

((3, 5, 4, 1), 4)

In [43]:
a.reshape(3, 5, 2, 1, 2)

array([[[[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]]],



       [[[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]]],



       [[[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]]]]])

In [48]:
a

array([[[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]]])

In [49]:
a = np.resize(a, (3, 5, 4, 3))
print(a)

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


In [44]:
b = np.ones((3, 5, 4, 1))
b.resize((3, 5, 4, 2))

In [47]:
b.resize()

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
   

In [51]:
a = np.ones((3, 500, 1000))

In [ ]:
3*w*h

In [ ]:
1*kanal*1*w*1*h

In [ ]:
expand_dims

In [58]:
a.shape
# 0, 2, 4

(3, 500, 1000)

In [62]:
b = np.expand_dims(a, axis=(0, 2, 4))
b.shape

(1, 3, 1, 500, 1, 1000)

In [63]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [65]:
np.expand_dims(a, axis=(0, 2))

array([[[1],
        [2],
        [3]]])

In [71]:
b.squeeze(axis=(0, 2)).shape

(3, 500, 1, 1000)

In [78]:
np.pad(a, pad_width=(2, 3), mode='edge')

array([1, 1, 1, 2, 3, 3, 3, 3])

In [81]:
b.reshape(3, 500, 200, -1).shape

(3, 500, 200, 5)

### Делаем массивы плоскими

In [90]:
b.shape # -> 1500000

(1, 3, 1, 500, 1, 1000)

In [93]:
c = np.ravel(b)
c.shape, b.shape

((1500000,), (1, 3, 1, 500, 1, 1000))

In [94]:
b.ravel()

array([1., 1., 1., ..., 1., 1., 1.])

In [95]:
b.flatten()

array([1., 1., 1., ..., 1., 1., 1.])

In [96]:
np.flatten(b)

AttributeError: module 'numpy' has no attribute 'flatten'

In [98]:
type(b.reshape(-1))

numpy.ndarray

In [100]:
a = np.array([[1, 2, 3], [3, 4, 5]])
a, list(a)

(array([[1, 2, 3],
        [3, 4, 5]]),
 [array([1, 2, 3]), array([3, 4, 5])])

In [104]:
type(a.tolist()[0])

list

### Преобразование массивов (вставка, разбивка)

In [117]:
a = np.array([[1, 2, 3], [3, 4, 5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [119]:
a.shape

(2, 3)

In [120]:
np.split(a, 3, axis=1)

[array([[1],
        [3]]),
 array([[2],
        [4]]),
 array([[3],
        [5]])]

In [121]:
a.shape

(2, 3)

In [126]:
np.insert(a, (1, 2), (1000, 500))

array([   1, 1000,    2,  500,    3,    3,    4,    5])

In [140]:
a.shape

(2, 3)

In [144]:
np.append(a, values=[[100], [100]])

array([  1,   2,   3,   3,   4,   5, 100, 100])

In [146]:
a = np.append(a, [[1, 2, 3]], axis=0)

In [148]:
a = np.append(a, [[1], [1], [1]], axis=1)

In [149]:
a

array([[1, 2, 3, 1],
       [3, 4, 5, 1],
       [1, 2, 3, 1]])

In [156]:
els, inxs = np.unique(a, axis=0, return_index=True)

In [157]:
els

array([[1, 2, 3, 1],
       [3, 4, 5, 1]])

In [158]:
inxs

array([0, 1], dtype=int64)

In [159]:
els, inxs = np.unique(a, axis=0, return_inverse=True)

In [160]:
els, inxs

(array([[1, 2, 3, 1],
        [3, 4, 5, 1]]),
 array([0, 1, 0], dtype=int64))

In [161]:
els[inxs]

array([[1, 2, 3, 1],
       [3, 4, 5, 1],
       [1, 2, 3, 1]])

In [162]:
els, cnt = np.unique(a, axis=0, return_counts=True)

In [163]:
els, cnt

(array([[1, 2, 3, 1],
        [3, 4, 5, 1]]),
 array([2, 1], dtype=int64))

In [173]:
np.tile(a, (1, 3))

array([[1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 3, 1],
       [3, 4, 5, 1, 3, 4, 5, 1, 3, 4, 5, 1],
       [1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 3, 1]])

In [172]:
np.repeat(a, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [3, 3, 3, 4, 4, 4, 5, 5, 5, 1, 1, 1],
       [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

Объединение массивов и конкатенация

In [174]:
a

array([[1, 2, 3, 1],
       [3, 4, 5, 1],
       [1, 2, 3, 1]])

In [175]:
b = np.repeat(a, 3, axis=1)

In [178]:
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [3, 4, 5, 1, 3, 3, 3, 4, 4, 4, 5, 5, 5, 1, 1, 1],
       [1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

In [179]:
c = a.copy()

In [183]:
np.concatenate((a, c*2), axis=1)

array([[ 1,  2,  3,  1,  2,  4,  6,  2],
       [ 3,  4,  5,  1,  6,  8, 10,  2],
       [ 1,  2,  3,  1,  2,  4,  6,  2]])

In [184]:
a.shape, b.shape

((3, 4), (3, 12))

In [190]:
np.hstack((a, b))

array([[1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1],
       [3, 4, 5, 1, 3, 3, 3, 4, 4, 4, 5, 5, 5, 1, 1, 1],
       [1, 2, 3, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1]])

In [191]:
np.vstack((a, b))
# stack, dstack

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 12

#### Другие полезные функции

In [198]:
a

array([[1, 2, 3, 1],
       [3, 4, 5, 1],
       [1, 2, 3, 1]])

In [199]:
a.prod(axis=0)

array([ 3, 16, 45,  1])

In [195]:
np.array([]).prod()

1.0

In [201]:
b = a*1.02568

In [202]:
b

array([[1.02568, 2.05136, 3.07704, 1.02568],
       [3.07704, 4.10272, 5.1284 , 1.02568],
       [1.02568, 2.05136, 3.07704, 1.02568]])

In [203]:
b.round(2)

array([[1.03, 2.05, 3.08, 1.03],
       [3.08, 4.1 , 5.13, 1.03],
       [1.03, 2.05, 3.08, 1.03]])

In [204]:
a.sort()

In [209]:
np.sort(b, axis=0)

array([[1.02568, 2.05136, 3.07704, 1.02568],
       [1.02568, 2.05136, 3.07704, 1.02568],
       [3.07704, 4.10272, 5.1284 , 1.02568]])

In [215]:
np.argsort(b, axis=None)

array([ 0,  3,  7,  8, 11,  1,  9,  2,  4, 10,  5,  6], dtype=int64)

In [216]:
arr = np.array([1, 2, 0, 3, 5, -4, 2])
np.argmin(arr)

5

In [217]:
np.argmax(arr)

4

In [5]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [226]:
np.diag(a, k=-1)

array([5])

#### WHERE - фильтрация

In [6]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
np.where(a%2 == 1)

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 3, 0, 2, 4], dtype=int64))

In [22]:
a[np.where(a%2 == 1)]

array([1, 3, 5, 7, 9])

In [24]:
np.where((a%2 == 1) & (a > 3))

(array([1, 1, 1], dtype=int64), array([0, 2, 4], dtype=int64))

In [25]:
np.where(np.logical_and(a%2 == 1, a > 3))

(array([1, 1, 1], dtype=int64), array([0, 2, 4], dtype=int64))

In [26]:
np.where((a%2 == 1) | (a > 3))

(array([0, 0, 0, 1, 1, 1, 1, 1], dtype=int64),
 array([1, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [27]:
np.where(np.logical_or(a%2 == 1, a > 3))

(array([0, 0, 0, 1, 1, 1, 1, 1], dtype=int64),
 array([1, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [28]:
np.where(a > 5, a, -1)

array([[-1, -1, -1, -1, -1],
       [-1,  6,  7,  8,  9]])

In [29]:
np.where(a > 5, a, a**2)

array([[ 0,  1,  4,  9, 16],
       [25,  6,  7,  8,  9]])