In [1]:
import numpy as np

**Загружаем данные**

In [67]:
float_formatter = "{:.2f}".format
np.set_printoptions(formatter={'float_kind': float_formatter})

In [61]:
data = np.genfromtxt('data/data.csv', delimiter=',', skip_header=True)

In [68]:
data

array([[2016.00, 1.00, 1.00, ..., 11.65, 69.99, 1.00],
       [2016.00, 1.00, 1.00, ..., 8.00, 54.30, 1.00],
       [2016.00, 1.00, 1.00, ..., 0.00, 37.80, 2.00],
       ...,
       [2016.00, 6.00, 30.00, ..., 5.00, 63.34, 1.00],
       [2016.00, 6.00, 30.00, ..., 8.95, 44.75, 1.00],
       [2016.00, 6.00, 30.00, ..., 0.00, 54.84, 2.00]])

In [69]:
data.shape

(89560, 15)

**Посчитаем среднюю скорость такси**

In [72]:
speed_arr = data[:, 7] / (data[:, 8]/3600)
speed_arr.mean()

32.24258580925573

**Посчитаем количество поездок в Феврале**

In [75]:
data[data[:, 1] == 2].shape[0]

13333

**Посчитаем количество поездок с чаевыми более 50 долларов**

In [76]:
data[data[:, -3] > 50].shape[0]

16

In [85]:
data[~np.isnan(np.where(data[:, -3] > 50, data[:, -3], np.nan))]

array([[2016.00, 1.00, 1.00, 5.00, 0.00, 4.00, 2.00, 21.45, 2004.00,
        52.00, 0.80, 0.00, 52.80, 105.60, 1.00],
       [2016.00, 1.00, 11.00, 1.00, 0.00, 3.00, 4.00, 9.20, 1041.00,
        27.00, 1.30, 5.54, 60.00, 93.84, 1.00],
       [2016.00, 1.00, 27.00, 3.00, 5.00, 2.00, 0.00, 19.80, 1671.00,
        52.50, 1.30, 5.54, 59.34, 118.68, 1.00],
       [2016.00, 2.00, 19.00, 5.00, 2.00, 4.00, 2.00, 18.42, 2968.00,
        52.00, 0.80, 5.54, 80.00, 138.34, 1.00],
       [2016.00, 3.00, 9.00, 3.00, 4.00, 3.00, 6.00, 0.49, 158.00, 3.50,
        1.80, 0.00, 70.00, 75.30, 1.00],
       [2016.00, 3.00, 17.00, 4.00, 1.00, 2.00, 2.00, 2.70, 381.00, 9.50,
        0.80, 0.00, 60.00, 70.30, 1.00],
       [2016.00, 3.00, 29.00, 2.00, 2.00, 3.00, 4.00, 9.54, 1210.00,
        27.50, 0.80, 5.54, 55.00, 88.84, 1.00],
       [2016.00, 4.00, 29.00, 5.00, 3.00, 2.00, 4.00, 17.60, 3251.00,
        52.00, 0.80, 5.54, 65.00, 123.34, 1.00],
       [2016.00, 5.00, 16.00, 1.00, 3.00, 4.00, 2.00, 38.20, 9

**Оценим взаимосвязи между переменными**

In [87]:
np.cov(data, rowvar=False)

array([[0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
        0.00, 0.00, 0.00, 0.00],
       [0.00, 2.86, -0.11, -0.03, -0.03, 0.02, -0.01, -0.04, 203.37,
        0.44, 0.09, 0.03, -0.06, 0.51, 0.01],
       [0.00, -0.11, 75.59, -0.15, -0.05, 0.05, -0.02, -0.16, 259.87,
        0.29, 0.00, 0.09, -0.20, 0.18, 0.03],
       [0.00, -0.03, -0.15, 4.01, 0.17, 0.00, -0.08, 0.34, -108.82, 0.37,
        -0.25, -0.22, -0.30, -0.40, 0.03],
       [0.00, -0.03, -0.05, 0.17, 1.97, -0.22, 0.16, -0.08, -15.72,
        -0.40, 0.35, -0.25, -0.09, -0.40, 0.01],
       [0.00, 0.02, 0.05, 0.00, -0.22, 0.68, -0.28, -0.95, -83.91, -2.12,
        -0.06, 0.52, 0.24, -1.42, -0.05],
       [0.00, -0.01, -0.02, -0.08, 0.16, -0.28, 1.91, -1.66, -217.96,
        -4.83, 0.00, 0.23, -0.67, -5.27, 0.03],
       [0.00, -0.04, -0.16, 0.34, -0.08, -0.95, -1.66, 26.71, 3413.20,
        58.19, 0.54, 2.80, 6.67, 68.19, -0.11],
       [0.00, 203.37, 259.87, -108.82, -15.72, -83.91, -217.96, 3413.20,
  

In [92]:
np.cov(data[:, [7, 8, -2, -3]].T)

array([[26.71, 3413.20, 68.19, 6.67],
       [3413.20, 10489667.24, 11345.40, 924.20],
       [68.19, 11345.40, 269.92, 45.80],
       [6.67, 924.20, 45.80, 23.35]])